apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: eurekaserver
  name: eurekaserversvc
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    app: eurekaserver

